/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const MintLazyImport = createFileRoute('/mint')()
const BridgeLazyImport = createFileRoute('/bridge')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const MintLazyRoute = MintLazyImport.update({
  id: '/mint',
  path: '/mint',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/mint.lazy').then((d) => d.Route))

const BridgeLazyRoute = BridgeLazyImport.update({
  id: '/bridge',
  path: '/bridge',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/bridge.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/bridge': {
      id: '/bridge'
      path: '/bridge'
      fullPath: '/bridge'
      preLoaderRoute: typeof BridgeLazyImport
      parentRoute: typeof rootRoute
    }
    '/mint': {
      id: '/mint'
      path: '/mint'
      fullPath: '/mint'
      preLoaderRoute: typeof MintLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/bridge': typeof BridgeLazyRoute
  '/mint': typeof MintLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/bridge': typeof BridgeLazyRoute
  '/mint': typeof MintLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/bridge': typeof BridgeLazyRoute
  '/mint': typeof MintLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bridge' | '/mint'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bridge' | '/mint'
  id: '__root__' | '/' | '/bridge' | '/mint'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  BridgeLazyRoute: typeof BridgeLazyRoute
  MintLazyRoute: typeof MintLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  BridgeLazyRoute: BridgeLazyRoute,
  MintLazyRoute: MintLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/bridge",
        "/mint"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/bridge": {
      "filePath": "bridge.lazy.tsx"
    },
    "/mint": {
      "filePath": "mint.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
